version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - .:/setup
    networks:
      - mongo-compose-network


  web:
      build: .
      links: 
          - mongodb
      networks:
        - mongo-compose-network


networks: 
  mongo-compose-network:
    driver: bridge